spring.application.name=user
server.port=8081
spring.datasource.url= jdbc:postgresql://localhost:5432/db_wallet
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update