spring.application.name=wallet
server.port=8082
spring.datasource.url= jdbc:postgresql://localhost:5432/db_wallet
spring.datasource.username=postgres
spring.datasource.password=password
#spring.jpa.hibernate.ddl-auto=update

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=Transaction:br.com.coutinhocorp.wallet.model.Transaction

